### PR TITLE
Bug 1676145 - Setup CI 

### PR DESCRIPTION
**Pull request by brizental**
~~Not ready for review, just want to check if it works.~~

Ready for review :) Leaving the comment spam to illustrate the development process of the size check 🤣 I am aware these comments may get on our nerves at some point, but we can make them conditional when they do get annoying. I think there might be value in running this check on every commit anyways...

### CODE REVIEW

**Comment by brizental** [comment]
$content

**Comment by brizental** [comment]
| Build | Current size | New size | Increase |
|--:|---|---|---|
| browser | $browser_size_main | $browser_size | $browser_emoji $browser_delta |
| qt | $browser_size_main | $browser_size_main | $qt_emoji $qt_delta |

**Comment by brizental** [comment]
| Build | Current size | New size | Size increase |
|--:|---|---|---|
| browser | 4551 | 4551 |  0 |
| qt | 4551 | 4551 |  0 |

**Comment by brizental** [comment]
# Build size report

  Merging https://github.com/brizental/glean.js/pull/5 into git@github.com:brizental/glean.js.git will:

  * **Decrease** by `0%`.
  * **Decrease** by `0%`.

  | Build | Current size | New size | Size increase |
  |--:|---|---|---|
  | browser | 4551B | 4551B | 📈 0% |
  | qt | 3470B | 3470B | 📈 0% |

**Comment by brizental** [comment]
# Build size report

  Merging https://github.com/brizental/glean.js/pull/5 into [main](https://github.com/brizental/glean.js) will:

  * **Decreases** the size of the browser build 
> glean@0.1.0 build:browser
> webpack --config webpack.config.browser.js --mode production

[webpack-cli] Compilation finished
asset glean.js 4.44 KiB [compared for emit] [minimized] (name: main)
./src/index.ts 831 bytes [built] [code generated]
webpack 5.4.0 compiled successfully in 1445 ms by `0%`.
  * **Decreases** the size of the qt build 
> glean@0.1.0 build:qt
> webpack --config webpack.config.qt.js --mode production

[webpack-cli] Compilation finished
asset glean.js 3.39 KiB [emitted] [minimized] (name: main)
./src/index.ts 831 bytes [built] [code generated]
webpack 5.4.0 compiled successfully in 1599 msby `0%`.

  ---

  | Build | Current size | New size | Size increase |
  |--:|---|---|---|
  | browser | 4551B | 4551B | 📈 0% |
  | qt | 3470B | 3470B | 📈 0% |

**Comment by brizental** [comment]
# Build size report

  Merging https://github.com/brizental/glean.js/pull/5 into [main](https://github.com/brizental/glean.js) will:

  * **Decreases** the size of the browser build `npm run build:browser` by `0%`.
  * **Decreases** the size of the qt build `npm run build:qt` by `0%`.

  ---

  | Build | Current size | New size | Size increase |
  |--:|---|---|---|
  | browser | 4551B | 4551B | 📈 0% |
  | qt | 3470B | 3470B | 📈 0% |

**Comment by brizental** [comment]
# Build size report

  Merging https://github.com/brizental/glean.js/pull/5 into [main](https://github.com/brizental/glean.js) will:

  * **Decreases** the size of the browser build `npm run build:browser` by `%`.
  * **Decreases** the size of the qt build `npm run build:qt` by `%`.

  ---

  | Build | Current size | New size | Size increase |
  |--:|:---:|:---:|:---:|
  | browser | 4.44K | 4.44K | 📈 % |
  | qt | 3.39K | 3.39K | 📈 % |

**Comment by brizental** [comment]
# Build size report

  Merging https://github.com/brizental/glean.js/pull/5 into [main](https://github.com/brizental/glean.js) will:

  * **Decreases** the size of the browser build `npm run build:browser` by `0%`.
  * **Decreases** the size of the qt build `npm run build:qt` by `0%`.

  ---

  | Build | Current size | New size | Size increase |
  |--:|:---:|:---:|:---:|
  | browser | 4.44K | 4.44K | 📈 0% |
  | qt | 3.39K | 3.39K | 📈 0% |

**Comment by brizental** [comment]
# Build size report

  Merging https://github.com/brizental/glean.js/pull/5 into [main](https://github.com/brizental/glean.js) will:

  * **Increases** the size of the browser build `npm run build:browser` by `0%`.
  * **Increases** the size of the qt build `npm run build:qt` by `0%`.

  ---

  | Build | Current size | New size | Size increase |
  |--:|:---:|:---:|:---:|
  | browser | 4.44K | 4.44K | 📈 0% |
  | qt | 3.39K | 3.39K | 📈 0% |

**Comment by brizental** [comment]
# Build size report

  Merging https://github.com/brizental/glean.js/pull/5 into [main](https://github.com/brizental/glean.js) will:

  * **Increase** the size of the browser build (`npm run build:browser`) by `0%`.
  * **Increase** the size of the Qt build (`npm run build:qt`) by `0%`.

  ---

  | Build | Current size | New size | Size increase |
  |--:|:---:|:---:|:---:|
  | browser | 4.44K | 4.44K | 📈 0% |
  | qt | 3.39K | 3.39K | 📈 0% |

**Comment by brizental** [comment]
# Build size report

  Merging https://github.com/brizental/glean.js/pull/5 into [main](https://github.com/brizental/glean.js) will:

  * **Increase** the size of the browser build (`npm run build:browser`) by `0%`.
  * **Increase** the size of the Qt build (`npm run build:qt`) by `0%`.

  ---

  | Build | Current size | New size | Size increase |
  |--:|:---:|:---:|:---:|
  | browser | 4.44K | 4.44K | 📈 0% |
  | qt | 3.39K | 3.39K | 📈 0% |

**Review by Dexterp37 — APPROVED** [review]
Very neat!

**Pull request merged**
